### ISSUE TITLE
Error downloading perception models

### ISSUE THREAD

**Issue by srajangoyal** [avstack-lab/carla-sandbox#1]
Hey guys, seems like a really cool project.
Have a few questions:

1. Error while downloading the mmdet models following the script:
  `cd submodules/lib-avstack-core/models
  ./download_mmdet_models.sh
  ./download_mmdet3d_models.sh`

```
----------------------------------------------------------------------------
Downloading models
--2023-06-13 11:58:08--  https://download.openmmlab.com/mmdetection/v2.0/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes/mask_rcnn_r50_fpn_1x_cityscapes_20201211_133733-d2858245.pth
Resolving download.openmmlab.com (download.openmmlab.com)... 47.246.46.204, 47.246.46.206, 47.246.46.210, ...
Connecting to download.openmmlab.com (download.openmmlab.com)|47.246.46.204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 176317048 (168M) [application/octet-stream]
Saving to: ‘./mmdet/checkpoints/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes_20201211_133733-d2858245.pth’

mask_rcnn_r50_fpn_1 100%[===================>] 168,15M  27,5MB/s    in 6,5s    

2023-06-13 11:58:15 (26,0 MB/s) - ‘./mmdet/checkpoints/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes_20201211_133733-d2858245.pth’ saved [176317048/176317048]

Downloading model and configuration for faster_rcnn_r50_fpn_1x_carla
--2023-06-13 11:58:15--  https://avstack-public-data.s3.amazonaws.com/models/mmdet/carla/faster_rcnn_r50_fpn_1x_carla.pth
Resolving avstack-public-data.s3.amazonaws.com (avstack-public-data.s3.amazonaws.com)... 3.5.29.141, 52.216.109.107, 52.216.217.89, ...
Connecting to avstack-public-data.s3.amazonaws.com (avstack-public-data.s3.amazonaws.com)|3.5.29.141|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-13 11:58:15 ERROR 404: Not Found.
-------------------------------------------------------------------------------------
```
Could you please check?

2. Is there an example config for simulating an ego with entire stack (perception, planning, control), i.e., using no ground truth info.?
  (I could try maybe adding planning and control modules in `LidarCameraPerceptionAndTrackingVehicle` or `LidarCamera3DFusionVehicle`, once I have the perception sub-modules, to see if that works.)

So far, I could only run `run_autopilot.sh` and `run_go_straight_agent.sh` from the examples.

Thanks!

**Comment by roshambo919** [comment]
Hi Srajan - thanks for pointing this out. We migrated recently from S3 to
Globus hosting, but I neglected to update the submodule reference pointers
for avstack-core and avstack-api. I'll fix it this evening and reference a
PR when it's done.

**Comment by srajangoyal** [comment]
Thank you so much.
I'm looking forward to it.

Just to confirm, are the ML models trained on the Carla simulator as well?
