### ISSUE TITLE
Carla-sandbox: up-to-date regarding avstack-core

### ISSUE THREAD

**Issue by MaxBial** [avstack-lab/carla-sandbox#3]
Hi Max - if you're running in a jupyter notebook, it would be better to use the [avdev sandbox](https://github.com/avstack-lab/avdev-sandbox) unless you're also using carla outside the notebook.

The avdev-sandbox is not yet up to date and neither is the carla-sandbox, but I'll try to update all dependencies by tomorrow afternoon. Let's discuss over there if you have issues after that.

_Originally posted by @roshambo919 in https://github.com/avstack-lab/lib-avstack-core/issues/11#issuecomment-1745725279_
            
 I saw that there are already some new updates on avdev-sandbox and I am curious if I can already use the carla-sandbox with its newest updates from avstack-core.
 
In the Readme of carla-sandbox still python 3.8 instead of 3.10 is mentioned - I guess the update is not ready yet, right? Do you know when we could expect the update?

Best Regards

**Comment by roshambo919** [comment]
Hi Max - thanks for migrating this here. What is left for me to do is build a carla wheel file for the python API for python 3.10. I'll try and do that ASAP and let you know when I'm finished.

**Comment by roshambo919** [comment]
@MaxBial I just finished the updates needed to build the carla python API with python 3.10. Can you try out the latest on your machine? I built the whl file on an Ubuntu 22 machine, so let me know if you run into any issues on 20.

**Comment by MaxBial** [comment]
Hi Spencer, I tested it now on my ubuntu 20.04 and it runs. A colleague of mine also tested it on ubuntu 22.04.
Now we are facing some other issues with AB3DMOT - I already opened a new issue and this issue could be closed.

Thanks
